version: "3.9"

services:
  db:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/data
    networks:
      - equi-net

  api:
    build:
      context: ./FacadeApi
      dockerfile: FacadeApi/Dockerfile
    container_name: api-core
    env_file:
      - .env
    ports:
      - "8082:8080"
      - "8083:8081"
    depends_on:
      - db
    networks:
      - equi-net
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio_server
    ports:
      - "9002:9000"
      - "9003:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - equi-net
   

volumes:
  pgdata:
  minio_data:

networks:
  equi-net:
